name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
defaults:
  run:
    shell: pwsh
jobs:
  Deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2   
      with:
        fetch-depth: 50
    - name: Import Modules
      run: |
        Import-Module PackageManagement -RequiredVersion 1.0.0.1
        Install-PackageProvider -Name NuGet -Force
        Find-Module IntelliTect* | Install-Module -Force

