name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
defaults:
  run:
    shell: pwsh
jobs:
 Deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2   
        with:
          fetch-depth: 2
      - id: DiscoverChanges
        run: |
          git diff --name-only HEAD HEAD~

