name: Pull Request

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  PesterTest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2      
      
      - name: Pester Test
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          script: |     
            $ConfirmPreference = "None"

            $testResults = Invoke-Pester -Script .\Modules.Tests\  -OutputFile ${{env.GITHUB_WORKSPACE}}\Test-Pester.XML -OutputFormat NUnitXML -PassThru
            if($testResults.FailedCount -ne 0) { 
                 Write-Error "$($testResults.FailedCount) test failed."
                 exit $LASTEXITCODE 
            }
  DotNetBuild:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2      
      
      - name: DotNet Bulid
        uses: Amadevus/pwsh-script@v2.0.1
        with: |
          $baseDir = (Get-Item -Path ".\" -Verbose).FullName
          $items = Get-ChildItem -Path $baseDir -Include *.sln -Recurse
          foreach ($item in $items){
              dotnet build $item
          }
      - name: DotNet Test
        uses: Amadevus/pwsh-script@v2.0.1
        with: |
          $baseDir = (Get-Item -Path ".\" -Verbose).FullName
          $items = Get-ChildItem -Path $baseDir -Include *.sln -Recurse
          foreach ($item in $items){
              dotnet test $item
          }
